// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALBSPIzoeD3GF4HuP34lG3YpOBOJWvUjY',
    appId: '1:46363687376:web:3438f013fdfb19acdca1d5',
    messagingSenderId: '46363687376',
    projectId: 'studyflutter-83b44',
    authDomain: 'studyflutter-83b44.firebaseapp.com',
    storageBucket: 'studyflutter-83b44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ZefWIPtmYTiJM9bRu8k8SIKdtE798Bg',
    appId: '1:46363687376:android:8d4b8675b5534e20dca1d5',
    messagingSenderId: '46363687376',
    projectId: 'studyflutter-83b44',
    storageBucket: 'studyflutter-83b44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiSpcltA9rV37NfAdoNlsVqlDkGSaEzBc',
    appId: '1:46363687376:ios:14ff5f28a45b752cdca1d5',
    messagingSenderId: '46363687376',
    projectId: 'studyflutter-83b44',
    storageBucket: 'studyflutter-83b44.firebasestorage.app',
    iosBundleId: 'com.example.studyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiSpcltA9rV37NfAdoNlsVqlDkGSaEzBc',
    appId: '1:46363687376:ios:14ff5f28a45b752cdca1d5',
    messagingSenderId: '46363687376',
    projectId: 'studyflutter-83b44',
    storageBucket: 'studyflutter-83b44.firebasestorage.app',
    iosBundleId: 'com.example.studyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALBSPIzoeD3GF4HuP34lG3YpOBOJWvUjY',
    appId: '1:46363687376:web:b68b630dab64c755dca1d5',
    messagingSenderId: '46363687376',
    projectId: 'studyflutter-83b44',
    authDomain: 'studyflutter-83b44.firebaseapp.com',
    storageBucket: 'studyflutter-83b44.firebasestorage.app',
  );
}
